### PR TITLE
Bump dependencies (levelup to 1.1!)

### PR DESCRIPTION
**Pull request by mcollina**
Bump the dependencies, and in particular levelup to 1.x.x.

I recommend a major version bump.

### CODE REVIEW

**Comment by dominictarr** [comment]
sorry I didn't see this, why major?

**Comment by dominictarr** [comment]
oh because level has a major bump... yeah okay

**Comment by mcollina** [comment]
yep :).

If you want some help maintaining this, you might consider it either moving it to the level org.
I can also help!

cc @ralphtheninja @juliangruber.

**Comment by dominictarr** [comment]
okay good idea,
merged into 2.0.0

**Comment by dominictarr** [comment]
@mcollina okay added you as npm owner.

**Comment by dominictarr** [comment]
transferred

**Comment by mcollina** [comment]
Great! Thanks @dominictarr :).

**Comment by ralphtheninja** [comment]
Cool!

**Pull request merged**
